spring.application.name=TravelLoop
spring.datasource.url=jdbc:mysql://localhost:3306/travelloop?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=Kavyaa1@skcet
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Security
jwt.secret=9a674738435d8866922d0571d79450a80e15f4e6629230588631f47851214040
jwt.expiration=86400000
